version: '3.8'

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=goblin
      - POSTGRES_PASSWORD=goblin
      - POSTGRES_DB=sites_mwitu_local

volumes:
  postgres_data: