version: '3.8'

services:
  api:
    build: ./api
    container_name: MwituApi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: MwituDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.db

volumes:
  postgres_data: