# Generated by Django 4.2 on 2023-04-13 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mwitu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='site',
            name='downvote',
            field=models.ManyToManyField(null=True, related_name='sites_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='upvote',
            field=models.ManyToManyField(null=True, related_name='sites_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
