# Generated by Django 4.2 on 2023-04-13 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mwitu', '0002_rename_description_site_about_site_downvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='sites_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='sites_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
