# Generated by Django 4.2 on 2023-07-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwitu', '0003_alter_review_comment_alter_site_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='managed_by',
            new_name='creatde_by',
        ),
    ]
