# Generated by Django 4.2 on 2023-04-13 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwitu', '0003_alter_site_downvote_alter_site_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
    ]
