# Generated by Django 4.2 on 2023-07-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwitu', '0004_rename_managed_by_site_creatde_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='creatde_by',
            new_name='created_by',
        ),
    ]
