# Generated by Django 4.2 on 2023-04-17 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mwitu', '0005_review_rating_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='site',
            name='upvote',
        ),
        migrations.AddField(
            model_name='review',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='reviews_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='reviews_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
